name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
          config: .markdownlint.json

  link-check:
    name: Link Checker (fast)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-${{ github.sha }}
          restore-keys: lychee-

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --cache
            --accept 200,206,429
            --no-progress
            --max-concurrency 8
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  schema-validate:
    name: Schema & Catalog Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Validate catalog
        run: npm run validate
      - name: Build TOCs
        run: npm run toc
      - name: Verify TOCs up-to-date
        run: |
          git status --porcelain
          git diff --quiet || (echo "TOCs are out of date. Run 'npm run toc' and commit." && git --no-pager diff && exit 1)