name: Java Smoke Tests

on:
  push:
    paths:
      - '03-java/**'
      - '.github/workflows/java-smoketests.yml'
  pull_request:
    paths:
      - '03-java/**'
      - '.github/workflows/java-smoketests.yml'

jobs:
  java-smoketests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Find Java projects
      id: find-projects
      run: |
        projects=$(find 03-java -name "pom.xml" -o -name "build.gradle" -o -name "build.gradle.kts" | xargs dirname | sort -u || true)
        if [ -z "$projects" ]; then
          echo "No Java projects found - this is expected for educational content"
          echo "found=false" >> $GITHUB_OUTPUT
        else
          echo "Found projects: $projects"
          echo "found=true" >> $GITHUB_OUTPUT
          echo "projects<<EOF" >> $GITHUB_OUTPUT
          echo "$projects" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Test Java projects
      if: steps.find-projects.outputs.found == 'true'
      run: |
        echo "${{ steps.find-projects.outputs.projects }}" | while IFS= read -r project_dir; do
          if [ -n "$project_dir" ]; then
            echo "Testing project in $project_dir"
            cd "$project_dir"

            if [ -f "pom.xml" ]; then
              # Maven project
              ./mvnw clean compile test || mvn clean compile test || echo "⚠️ Maven build/test issues in $project_dir"
            elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
              # Gradle project
              ./gradlew clean build test || gradle clean build test || echo "⚠️ Gradle build/test issues in $project_dir"
            fi

            cd - > /dev/null
          fi
        done

    - name: No projects found
      if: steps.find-projects.outputs.found == 'false'
      run: |
        echo "ℹ️ No Java projects found in 03-java/"
        echo "This is expected behavior for educational content without project seeds"
        echo "Workflow passes successfully"