name: Nightly Link Check

on:
  schedule:
    - cron: "17 2 * * *"  # daily at 02:17 UTC
  workflow_dispatch: {}
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-${{ github.sha }}
          restore-keys: lychee-

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --cache
            --no-progress
            --verbose
            --max-redirects 5
            --accept 200,206,429
            --max-concurrency 6
            --retry-wait-time 2
            --retry-count 2
            ./**/*.md
            ./**/*.html
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save lychee cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .lycheecache
          key: lychee-${{ github.sha }}