name: Python Template Tests

on:
  push:
    paths:
      - 'templates/python-cli/**'
      - '.github/workflows/python-templates.yml'
  pull_request:
    paths:
      - 'templates/python-cli/**'
      - '.github/workflows/python-templates.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        working-directory: templates/python-cli
        env:
          PYTHONPATH: .
        run: pytest -q